sudo: required
dist: trusty
language: ruby

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python python-dev python-pip python-virtualenv
  - sudo rm -rf /var/lib/apt/lists/*

install:

- sudo pip install -r requirements.txt

script:

- python -V
- pip freeze
- python test.py
