sudo: required
dist: trusty
language: ruby

services:
  - docker

language: python
python:
  - "3.4"
  - "2.7"

before_install:
  - docker run hello-world

# command to install dependencies
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:  python test.py
